[package]
name = "aoe2rec-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
aoe2rec = { path = "../aoe2rec" }
clap = { version = "4.5.53", features = ["derive"] }
tracing = "0.1.43"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
zip = "6.0.0"
